PrescriptionUI/Models/DoctorViewModel.cs
using PrescriptionBE;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using PrescriptionBL;

namespace PrescriptionUI.Models
{
    public class DoctorViewModel
    {
        public int Id { get; set; }
        public string DoctorId { get; set; }
        public string Name { get; set; }
        public string SpecialName { get; set; }
        [DisplayName("License Expiration Date")]
        public DateTime LicenseExpirationDate { get; set; }
        public List<string> specials { get; set; }
        public override string ToString()
        {
            return $"id:{Id} name:{Name} special:{SpecialName}";
        }
        public DoctorViewModel(Doctor doctor)
        {
            IBL bl = new BLImplement();
            DoctorId = doctor.DoctorId;
            Id = doctor.Id;
            Name = doctor.Name;
            SpecialName =bl.getAllSpecialties().Where(s=>s.Id== doctor.Special).FirstOrDefault().SpecialtyName;
            LicenseExpirationDate = doctor.LicenseExpirationDate;
            specials = bl.getAllSpecialties().Select(x => x.SpecialtyName).ToList();
        }
        public DoctorViewModel()
        {
            IBL bl = new BLImplement();
            Name = null;
            LicenseExpirationDate = DateTime.MinValue;
            specials = bl.getAllSpecialties().Select(x => x.SpecialtyName).ToList();
        }
    }
}

PrescriptionUI/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PrescriptionBL;
using PrescriptionUI.Models;
using PrescriptionBE;
using System.Net;

namespace PrescriptionUI.Controllers
{
    public class DoctorController : Controller
    {
        public ActionResult DoctorOptions(Doctor doctor=null)
        {
            var fdvm = new ForDoctorViewModel(doctor);
            return View(fdvm);
        }

        public ActionResult prescriptionIssuance(string id, string doctor)
        {
            IBL bl = new BLImplement();
            var d= bl.getDoctor(doctor);
            if(doctor==null)
            {
                ViewBag.Message = String.Format("please enter again");
                return RedirectToAction("DoctorEntrance","Home");
            }
            
            var pfpm = new PrescriptionForPatientModel();
            pfpm.prescription.Patient = id;
            pfpm.prescription.Doctor = doctor;
            pfpm.patient = id;
            pfpm.doctor = doctor;
            return View(pfpm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult prescriptionIssuance(FormCollection collection)///*string medicine*/, DateTime StartDate, DateTime EndDate, string Doctor, string Patient, string Cause)
        {
            try
            {
                IBL bl = new BLImplement();
                Prescription prescription = new Prescription()
                {
                    medicine = bl.getAllMedicines().FirstOrDefault(x => x.Name == collection["medicine"]).Id,//change the name to the id
                    StartDate =Convert.ToDateTime( collection["StartDate"]),
                    EndDate = Convert.ToDateTime(collection["EndDate"]),
                    Doctor = collection["Doctor"],
                    Patient = collection["Patient"],
                    Cause = collection["prescription.Cause"]
                };
                bl.addPrescription(prescription);
                ViewBag.Message = String.Format("The prescription for {0} is successfully added. You can watch {1}'s medical history for full details. ", collection["medicine"].ToString(), bl.getPatient(prescription.Patient).Name.ToString());
                return RedirectToAction("DoctorOptions"/*, prescription.Doctor*/);
            }
            catch (Exception ex)
            {
                ViewBag.Message = String.Format(ex.Message);
                return RedirectToAction("prescriptionIssuance");
            }
        }
        //public ActionResult medicalHistory(string id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    return RedirectToAction("Index", "Prescription", id);
        //}
    }
}

PrescriptionUI/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PrescriptionBE;
using PrescriptionBL;
using PrescriptionUI.Data;
using PrescriptionUI.Models;

namespace PrescriptionUI.Controllers
{
    public class DoctorsController : Controller
    {

        // GET: Doctors
        public ActionResult Index(string searchString="")
        {
            IBL bl = new BLImplement();
            List<DoctorViewModel> lst = new List<DoctorViewModel>();
            foreach (var item in bl.getAllDoctors())
            {
                lst.Add(new DoctorViewModel(item));
            }
            if (!String.IsNullOrEmpty(searchString))
            {
                lst = lst.Where(s => s.Name.ToLower().Contains(searchString.ToLower()) || s.SpecialName.ToLower().Contains(searchString.ToLower())).ToList();
            }
            return View(lst);
        }

        // GET: Doctors/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IBL bl = new BLImplement();
            Doctor doctor = bl.getDoctor(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            DoctorViewModel dvm = new DoctorViewModel(doctor);
            return View(dvm);
        }

        // GET: Doctors/Create
        public ActionResult Create()
        {
            var dvm = new DoctorViewModel();
            return View(dvm);
        }

        // POST: Doctors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DoctorId,Name,Special,LicenseExpirationDate")] DoctorViewModel dvm)
        {
            if (ModelState.IsValid)
            {
                IBL bl = new BLImplement();
                try
                {
                    if (!bl.getAllSpecialties().ToList().Exists(a => a.SpecialtyName == dvm.SpecialName))
                        bl.addSpecialty(new Specialty { SpecialtyName = dvm.SpecialName });
                }
                catch (Exception ex)
                {
                    ViewBag.Message = String.Format(ex.Message);
                    return RedirectToAction("Create");
                }
                if (!bl.getAllSpecialties().ToList().Exists(a => a.SpecialtyName == dvm.SpecialName))
                    bl.addSpecialty(new Specialty { SpecialtyName = dvm.SpecialName });
                Doctor doctor = new Doctor()
                {
                    Name = dvm.Name,
                    LicenseExpirationDate = Convert.ToDateTime(dvm.LicenseExpirationDate),
                    Special = bl.getAllSpecialties().Where(s => s.SpecialtyName == dvm.SpecialName).FirstOrDefault().Id
                };
                try
                {
                    bl.addDoctor(doctor);
                    ViewBag.Message = String.Format("The doctor {0} is successfully added", doctor.Name);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.Message = String.Format(ex.Message);
                    return RedirectToAction("Index");
                }
               
            }
            return View(dvm);
        }

        // GET: Doctors/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IBL bl = new BLImplement();
            Doctor doctor = bl.getDoctor(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            DoctorViewModel dvm = new DoctorViewModel(doctor);
            return View(dvm);
        }

        // POST: Doctors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DoctorId,Name,Special,LicenseExpirationDate")] DoctorViewModel dvm)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    IBL bl = new BLImplement();
                    var doctor = new Doctor()
                    {
                        DoctorId = dvm.DoctorId,
                        Name = dvm.Name,
                        LicenseExpirationDate = Convert.ToDateTime(dvm.LicenseExpirationDate),
                        Special =bl.getAllSpecialties().Where(s => s.SpecialtyName == dvm.SpecialName).FirstOrDefault().Id

                    };                
                    bl.updateDoctor(doctor);
                    ViewBag.Message = String.Format("The doctor {0} is successfully updated", doctor.Name);
                }
                catch (Exception ex)
                {
                    ViewBag.Message = String.Format(ex.Message);
                    return RedirectToAction("Index");
                }
                //db.Entry(doctorViewModel).State = EntityState.Modified;
                return RedirectToAction("Index");
            }
            return View(dvm);
        }

        // GET: Doctors/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IBL bl = new BLImplement();
            Doctor doctor = bl.getDoctor(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            DoctorViewModel dvm = new DoctorViewModel(doctor);
            return View(dvm);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            try
            {
                IBL bl = new BLImplement();
                Doctor doctor = bl.getDoctor(id);
                bl.deleteDoctor(doctor);
                ViewBag.Message = String.Format("The doctor {0} is successfully deledted", doctor.Name);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Message = String.Format(ex.Message);
                return RedirectToAction("Delete");
            }

        }
    }
}

PrescriptionUI/Controllers/PrescriptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PrescriptionBL;
using PrescriptionBE;
using PrescriptionUI.Models;
using System.Web.UI.WebControls;

namespace PrescriptionUI.Controllers
{
    public class PrescriptionController : Controller
    {
        // GET: Prescription
        public ActionResult Index(string id)//IEnumerable<Prescription> prescriptions)
        {
            IBL bl = new BLImplement();
            var patient = bl.getPatient(id);
            if(patient==null)
            {
                patient = bl.getAllPatients().FirstOrDefault(X => X.Name == id);//when return to list
            }
            var prescriptions = bl.allPrescriptionFromPatient(patient);
            if (prescriptions==null)
            {
                ViewBag.Message = String.Format("There are no prescription for {0} yet",patient.Name);
                return RedirectToAction("DoctorOptions");
            }
            var lst = new List<PrescriptionViewModel>();
            foreach (var item in prescriptions)
            {
                lst.Add(new PrescriptionViewModel(item));
            }
            return View(lst);
        }

        // GET: Prescription/Details/5
        public ActionResult Details(int id)
        {
            IBL bl = new BLImplement();           
            var pvm = new PrescriptionViewModel(bl.getAllPrescriptions().FirstOrDefault(x => x.Id == id));
            ViewBag.Patient = pvm.Patient;
            return View(pvm);
        }
    }
}

PrescriptionUI/Views/Doctor/DoctorOptions.cshtml
@model PrescriptionUI.Models.ForDoctorViewModel
@{
    ViewBag.Title = "DoctorOptions";
    Layout = "~/Views/Shared/DoctorLayout.cshtml";
}

<body>
    <section id="home-section" class="hero">
        <div class="home-slider owl-carousel">
            <div class="slider-item" style="background-image: url('../vegefoods/images/doctorOption.jpg');" alt="">
                <div class="overlay"></div>
                <div class="container">
                    <div class="row slider-text justify-content-center align-items-center" data-scrollax-parent="true">
                        <div class="col-md-12 ftco-animate text-center">
                            <h1 class="mb-2">Hi  @Model.doctor.Name</h1>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

@using (Html.BeginForm("prescriptionIssuance", "Doctor"))
{
    <section class="ftco-section ftco-cart">
        <div class="container">
            <div class="row">
                <div class="col-md-12 ftco-animate">
                    <div class="cart-list">
                        <table class="table">
                            <thead class="thead-primary">
                                <tr class="text-center">
                                    <th>Name</th>
                                    <th>Id</th>
                                    <th>&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.patients)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PatientId)
                                        </td>
                                        <td>
                                            @Html.ActionLink("prescription Issuance", "prescriptionIssuance", new { id = item.PatientId, doctor = Model.doctor.DoctorId }) |
                                            @*@Html.ActionLink("medical history", "medicalHistory", new { id = item.PatientId })*@
                                            @Html.ActionLink("medical history", "Index","Prescription", new { id = item.PatientId },null)
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
}‏

PrescriptionUI/Views/Doctor/prescriptionIssuance.cshtml
@model PrescriptionUI.Models.PrescriptionForPatientModel

@{
    ViewBag.Title = "prescriptionIssuance";
    Layout = "~/Views/Shared/DoctorLayout.cshtml";
}

@if (ViewBag.Message != null)
{
<script type="text/javascript">

            window.onload = function () {
                alert("@ViewBag.Message");
            };
</script>}

@using (Html.BeginForm("prescriptionIssuance", "Doctor"))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Fill in the prescription details below please:</h4>
    <hr />

    @Html.HiddenFor(model => model.doctor)
    @Html.HiddenFor(model => model.patient)

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div>
            @*@Html.EditorFor(model => model.prescription.medicine, new { htmlAttributes = new { @class = "form-control" } })
                @Html.DropDownListFor(m => m.prescription.medicine, new SelectList(Model.medicines), "Select Medicine"))*@

            @Html.DropDownListForUsers("medicine")
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.prescription.StartDate, htmlAttributes: new { @class = "control-label col-md-10" })
        <div class="col-md-10">
            <input type="date" id="StartDate" name="StartDate" required="" style="position:relative; width:315px;" class="form-control text-dark" placeholder="start" />
        </div>

    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.prescription.EndDate, htmlAttributes: new { @class = "control-label col-md-10" })
        <div class="col-md-10">
            <input type="date" id="EndDate" name="EndDate" required="" style="position:relative; width:315px;" class="form-control text-dark" placeholder="start" />
        </div>

    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.prescription.Cause, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.prescription.Cause, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.prescription.Cause, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-black py-3 px-5" />
        </div>
    </div>
</div>
}‏