PrescriptionUI/Models/MedicineViewModel.cs
using PrescriptionBE;
using PrescriptionBL;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace PrescriptionUI.Models
{
    public class MedicineViewModel
    {
        public int Id { get; set; }

        [DisplayName("Medicine Name")]
        public string Name { get; set; }
        public string Producer { get; set; }
        [DisplayName("Generic Name")]
        public string GenericName { get; set; }
        public string ActiveIngredients { get; set; }
        public string PortionProperties { get; set; }

        [DisplayName("Upload File")]
        public string Picture { get; set; }
        public override string ToString()
        {
            return $"id:{Id} name:{Name}";
        }
        public MedicineViewModel()
        {
            Name = null;
            Producer = null;
            ActiveIngredients = null;
            PortionProperties = null;
            GenericName = null;
            Picture = null;
        }
        public MedicineViewModel(Medicine medicine)
        {
            IBL bl = new BLImplement();
            this.Id = medicine.Id;
            this.Name = medicine.Name;
            this.GenericName = medicine.GenericName;
            this.PortionProperties = medicine.PortionProperties;
            this.Producer = medicine.Producer;
            this.Picture = bl.getMedicinePicture(Id);
        }
    }
}

PrescriptionUI/Controllers/MedicineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using PrescriptionBL;
using PrescriptionUI.Data;
using PrescriptionUI.Models;
using PrescriptionBE;
using System.Net;

namespace PrescriptionUI.Controllers
{
    public class MedicineController : Controller
    {
        // GET: Medicine
        public ActionResult Index(string searchString="")
        {
            IBL bl = new BLImplement();
            List<MedicineViewModel> lst = new List<MedicineViewModel>();             
            var temp = bl.getAllMedicines().Where(a => a.Id <= 20).ToList();
            foreach (var item in temp)
            {
                lst.Add(new MedicineViewModel(item));
            }
            if (!String.IsNullOrEmpty(searchString))
            {
                lst = lst.Where(s => s.Name.Contains(searchString) || s.GenericName.Contains(searchString)).ToList();
            }
            return View(lst);
        }

        // GET: Medicine/Details/5
        public ActionResult Details(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IBL bl = new BLImplement();
            Medicine medicine = bl.getMedicine(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            var mvm = new MedicineViewModel(medicine);
            return View(mvm);
        }

        // GET: Medicine/Create
        public ActionResult Create()
        {
            var mvm = new MedicineViewModel();
            return View(mvm);
        }

        // POST: Medicine/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MedicineViewModel mvm, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                IBL bl = new BLImplement();
                Medicine medicine = new Medicine()
                {
                    Name = mvm.Name,
                    GenericName = mvm.GenericName,
                    ActiveIngredients = mvm.ActiveIngredients,
                    PortionProperties = mvm.PortionProperties,
                    Producer = mvm.Producer
                };
                try
                {
                    if (ImageFile != null)
                    {
                        bl.addMedicine(medicine);
                    }
                    else
                    {
                        bl.addMedicine(medicine, ImageFile);
                    }
                    bl.addMedicine(medicine, ImageFile);
                    ViewBag.Message = String.Format("The medicine {0} is successfully added", medicine.Name);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.Message = String.Format(ex.Message);
                    return RedirectToAction("Index");
                }
            }

            return View(new MedicineViewModel());
        }

        // GET: Medicine/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IBL bl = new BLImplement();
            Medicine medicine = bl.getMedicine(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            MedicineViewModel mvm = new MedicineViewModel(medicine);
            return View(mvm);
        }

        // POST: Medicine/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, MedicineViewModel mvm, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                IBL bl = new BLImplement();
                Medicine medicine = new Medicine()
                {
                    Id=mvm.Id,
                    Name = mvm.Name,
                    GenericName = mvm.GenericName,
                    ActiveIngredients = mvm.ActiveIngredients,
                    PortionProperties = mvm.PortionProperties,
                    Producer = mvm.Producer

                };
                try
                {
                    if (ImageFile != null)
                    { bl.updateMedicinePicture(medicine.Id, ImageFile); }                   
                    bl.updateMedicine(medicine);
                    ViewBag.Message = String.Format("The Medicine {0} successfully updated", medicine.Name);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.Message = String.Format(ex.Message);
                    return RedirectToAction("Index");
                }
            }
            return View(new MedicineViewModel());
        }

        // GET: Medicine/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IBL bl = new BLImplement();
            Medicine medicine = bl.getMedicine(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            MedicineViewModel mvm = new MedicineViewModel(medicine);
            return View(mvm);
        }

        // POST: Medicine/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                IBL bl = new BLImplement();
                Medicine medicine = bl.getMedicine(id);
                bl.deleteMedicine(medicine);
                ViewBag.Message = String.Format("The medicine {0} is successfully deleted", medicine.Name);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Message = String.Format(ex.Message);
                return RedirectToAction("Index");
            }
        }
    }
}

PrescriptionUI/Controllers/MedicinesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PrescriptionBE;
using PrescriptionBL;
using PrescriptionUI.Data;
using PrescriptionUI.Models;


namespace PrescriptionUI.Controllers
{
    public class MedicinesController : Controller
    {

        // GET: Medicines
        public ActionResult Index()
        {
            IBL bl = new BLImplement();
            List<MedicineViewModel> lst = new List<MedicineViewModel>();
            foreach (var item in bl.getAllMedicines())
            {
                lst.Add(new MedicineViewModel(item));
            }
            return View(lst);
        }

        // GET: Medicines/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IBL bl = new BLImplement();
            Medicine medicine = bl.getAllMedicines().FirstOrDefault(x => x.Id == id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            var mvm = new MedicineViewModel(medicine);
            return View(mvm);
        }

        // GET: Medicines/Create
        public ActionResult Create()
        {
            var mvm = new MedicineViewModel();
            return View(mvm);
        }

        // POST: Medicines/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MedicineViewModel mvm,HttpPostedFileBase ImageFile)//[Bind(Include = "Id,Name,Producer,GenericName,ActiveIngredients,PortionProperties")] MedicineViewModel mvm)
        {
            if (ModelState.IsValid)
            {
                IBL bl = new BLImplement();
                Medicine medicine = new Medicine()
                {
                    //Name = collection["Name"],
                    //GenericName = collection["GenericName"],
                    //ActiveIngredients = collection["ActiveIngredients"],
                    //PortionProperties = collection["PortionProperties"],
                    //Producer = collection["Producer"]
                    Name = mvm.Name,
                    GenericName = mvm.GenericName,
                    ActiveIngredients = mvm.ActiveIngredients,
                    PortionProperties = mvm.PortionProperties,
                    Producer = mvm.Producer

                };
                try
                {
                    bl.addMedicine(medicine, ImageFile);
                    ViewBag.Message = String.Format("The medicine {0} is successfully added", medicine.Name);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.Message = String.Format(ex.Message);
                    return RedirectToAction("Index");
                }
            }

            return View(new MedicineViewModel());
        }


        // GET: Medicines/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IBL bl = new BLImplement();
            Medicine medicine = bl.getAllMedicines().ToList().FindAll(x => x.Id == id).FirstOrDefault();
            if (medicine == null)
            {
                return HttpNotFound();
            }
            MedicineViewModel mvm = new MedicineViewModel(medicine);
            return View(mvm);
        }

        // POST: Medicines/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MedicineViewModel mvm, HttpPostedFileBase ImageFile)//[Bind(Include = "Id,Name,Producer,GenericName")] MedicineViewModel mvm)
        {
            if (ModelState.IsValid)
            {
                IBL bl = new BLImplement();
                Medicine medicine = new Medicine()
                {
                    Name = mvm.Name,
                    GenericName = mvm.GenericName,
                    ActiveIngredients = mvm.ActiveIngredients,
                    PortionProperties = mvm.PortionProperties,
                    Producer = mvm.Producer

                };
                try
                {
                    bl.addMedicine(medicine, ImageFile);
                    ViewBag.Message = String.Format("The Medicine {0} successfully updated", medicine.Name);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.Message = String.Format(ex.Message);
                    return RedirectToAction("Index");
                }
            }
            return View(new MedicineViewModel());
        }

        // GET: Medicines/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IBL bl = new BLImplement();
            Medicine medicine = bl.getAllMedicines().ToList().FindAll(x => x.Id == id).FirstOrDefault();
            if (medicine == null)
            {
                return HttpNotFound();
            }
            return View(medicine);
        }

        // POST: Medicines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                IBL bl = new BLImplement();
                Medicine medicine = bl.getAllMedicines().ToList().FindAll(x => x.Id == id).FirstOrDefault();
                bl.deleteMedicine(medicine);
                ViewBag.Message = String.Format("The medicine {0} is successfully deleted", medicine.Name);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Message = String.Format(ex.Message);
                return RedirectToAction("Index");
            }
        }

    }
}

PrescriptionUI/Views/Medicine/Create.cshtml
@model PrescriptionUI.Models.MedicineViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/OptionsLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Medicine", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Medicine</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Producer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Producer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Producer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenericName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GenericName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GenericName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PortionProperties, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PortionProperties, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PortionProperties, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActiveIngredients, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActiveIngredients, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActiveIngredients, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="img" name="ImageFile" accept="image/*" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PrescriptionUI/Views/Medicine/Delete.cshtml
@model PrescriptionUI.Models.MedicineViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/OptionsLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Medicine</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Producer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Producer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GenericName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GenericName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActiveIngredients)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActiveIngredients)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PortionProperties)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PortionProperties)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-black py-3 px-5" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PrescriptionUI/Views/Medicine/Details.cshtml
@model PrescriptionUI.Models.MedicineViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/OptionsLayout.cshtml";
}

<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 mb-5 ftco-animate fadeInUp ftco-animated">
                <a class="image-popup"><img src="@Url.Content(Model.Picture)" class="img-fluid" alt="Colorlib Template"></a>
            </div>
            <div class="col-lg-6 product-details pl-md-5 ftco-animate fadeInUp ftco-animated">
                <h3>@Model.Name</h3>
                <div class="rating d-flex">
                    <p class="text-left mr-4">
                        <a href="#" class="mr-2">Producer: @Model.Producer</a>
                    </p>
                </div>
                <p class="price"><span>@Model.GenericName</span></p>
                <p>
                    More Details:
                    The Medicine's active ingredients are: @Model.ActiveIngredients , and the portion properties is: @Model.PortionProperties .
                </p>
                <a class="btn btn-black py-3 px-5" @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) </a>
            </div>
        </div>
    </div>
</section>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

PrescriptionUI/Views/Medicine/Edit.cshtml
@model PrescriptionUI.Models.MedicineViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/OptionsLayout.cshtml";
}
@if (ViewBag.Message != null)
{
    <script type="text/javascript">

            window.onload = function () {
                alert("@ViewBag.Message");
            };
    </script>

}
@using (Html.BeginForm("Edit", "Medicine", FormMethod.Post ,new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <section class="ftco-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mb-5 ftco-animate fadeInUp ftco-animated">
                    <a class="image-popup"><img src="@Url.Content(Model.Picture)" class="img-fluid"></a>
                </div>
                <div class="col-lg-6 product-details pl-md-5 ftco-animate fadeInUp ftco-animated">
                    <p>
                        Name:

                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </p>
                    <p>
                        Producer:

                        @Html.EditorFor(model => model.Producer, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Producer, "", new { @class = "text-danger" })
                    </p>
                    <p>
                        Generic Name:
                        @Html.EditorFor(model => model.GenericName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.GenericName, "", new { @class = "text-danger" })
                    </p>
                    <p>
                        Active Ingredients
                        @Html.EditorFor(model => model.ActiveIngredients, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ActiveIngredients, "", new { @class = "text-danger" })
                    </p>
                    <p>
                        Portion Properties:
                        @Html.EditorFor(model => model.PortionProperties, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PortionProperties, "", new { @class = "text-danger" })
                    </p>
                    <p>
                        Picture:
                        <div class="input-group">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="ImageFile" name="ImageFile" accept="image/*">
                                <label class="custom-file-label" for="ImageFile">Choose file</label>
                            </div>
                        </div>
                    </p>
                    <div class="form-group">
                        <div>
                            <input type="submit" value="Save" class="btn btn-black py-3 px-5" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        $('.custom-file-input').on('change', function () {
            let fileName = $(this).val().split('\\').pop();
            $(this).next('.custom-file-label').addClass("selected").html(fileName);
        });
    </script>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PrescriptionUI/Views/Medicine/Index.cshtml
@model IEnumerable<PrescriptionUI.Models.MedicineViewModel>

@{
    ViewBag.Title = "medicines";
    Layout = "~/Views/Shared/OptionsLayout.cshtml";
}
@if (ViewBag.Message != null)
{
    <script type="text/javascript">

            window.onload = function () {
                alert("@ViewBag.Message");
            };
    </script>

}
<div class="hero-wrap hero-bread" style=" background-image: url('../vegefoods/images/medicines.jpg');" alt="">

    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center fadeInUp ftco-animated">
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Products</span></p>
                <h1 class="mb-0 bread">Products</h1>
            </div>
        </div>
    </div>
</div>
<p>
    @Html.ActionLink("Create New", "Create")
</p>


<section class="ftco-section">
    <form class="form-control" asp-controller="Search" asp-action="Index">
        <p>
            <input type="text" name="SearchString">
            <input class="btn" type="submit" value="Filter" />
        </p>
    </form>
    <br /><br />
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-6 col-lg-3 ftco-animate fadeInUp ftco-animated">
                    <div class="product">
                        <a href="#" class="img-prod">
                            <img class="img-fluid" src="@Url.Content(item.Picture)">
                            <div class="overlay"></div>
                        </a>
                        <div class="text py-3 pb-4 px-3 text-center">
                            <h3><a href="#">@item.Name</a></h3>
                            <div class="d-flex">
                                <div class="pricing">
                                    <p class="price"><span class="price-sale">@item.GenericName</span></p>
                                </div>
                            </div>
                            <div class="bottom-area d-flex px-3">
                                <div class="m-auto d-flex">
                                    @*@Html.NoEncodeActionLink("<i class=\"glyphicon glyphicon-trash\"></i>", "Edit", new { id = item.Id, @class = "ion-ios-menu" })*@
                                    @Html.ActionLink("edit", "Edit", new { id = item.Id }, new { @class = "glyphicon glyphicon-trash" })
                                    @Html.ActionLink("details", "Details", new { id = item.Id }, new { @class = "ion-ios-menu" })
                                    @Html.ActionLink("delete", "Delete", new { id = item.Id }, new { @class = "ion-ios-menu" })
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            }
        </div>
        <div class="row mt-5">
        </div>
    </div>
</section>